server.port=${PORT:8082}
logging.level.org.atmosphere = warn

vaadin.launch-browser=false
vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,com.sbsolutions

server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring.main.allow-bean-definition-overriding=true

# Actuator configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

# Order Data service configuration
ORDER_DATA_REST_URL=https://order-data.fly.dev
